/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Mapas.Bosque;

/**
 *
 * @author dalvarezruiz
 * @author jquesadaabeijon
 */
public class ventanaGeneral extends javax.swing.JFrame {
    Bosque forest = new Bosque();
    
    
    /**
     * Creates new form ventanaGeneral
     */
    public ventanaGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 720));
        setPreferredSize(new java.awt.Dimension(520, 710));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chevron-que-apunta-a-la-izquierda.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setPreferredSize(new java.awt.Dimension(60, 35));
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 560, 60, 35);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chevron-flecha-hacia-arriba.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setPreferredSize(new java.awt.Dimension(60, 35));
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 540, 60, 35);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chevron-apuntando-hacia-la-derecha.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setMaximumSize(new java.awt.Dimension(60, 35));
        jButton3.setMinimumSize(new java.awt.Dimension(60, 35));
        jButton3.setPreferredSize(new java.awt.Dimension(60, 35));
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 560, 60, 35);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-chevron-hacia-abajo.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setPreferredSize(new java.awt.Dimension(60, 35));
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 580, 60, 35);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 51));
        jButton5.setText("Volver a dormir");
        jButton5.setFocusable(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 620, 260, 30);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Usar");
        jButton6.setFocusable(false);
        getContentPane().add(jButton6);
        jButton6.setBounds(385, 520, 100, 37);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Examinar");
        jButton7.setFocusable(false);
        getContentPane().add(jButton7);
        jButton7.setBounds(220, 520, 160, 37);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pssm_map05.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 280, 470, 210);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 12)); // NOI18N
        jLabel2.setText("<html><p>Te internas en el bosque y te das cuenta de que\nes mucho más profundo de lo que creías. La luz\napenas es capaz de atravesar las frondosas ramas\nde los árboles. Hacia el Este ves un reflejo, quizá\nsea agua. Hacia el Oeste ves un pequeño camino\nque parece meterse entre los árboles. Hacia el Norte\nves otro camino y una señal en el suelo que dice ‘NO PASAR’.</p>\n<br></br>\n<p>1. Vas a inspeccionar el reflejo.</p> \n<p>2. Vas por el camino entre los árboles.</p> \n<p>3.Ignoras la señal del suelo y te diriges hacia el Norte.</p>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 280, 200);
        jLabel2.getAccessibleContext().setAccessibleName("Te internas en el bosque y te das cuenta de que \nes mucho más profundo de lo que creías. La luz \napenas es capaz de atravesar las frondosas ramas \nde los árboles. Hacia el Este ves un reflejo, quizá \nsea agua. Hacia el Oeste ves un pequeño camino \nque parece meterse entre los árboles. Hacia el Norte \nves otro camino y una señal en el suelo que dice ‘NO PASAR’.\n\n1. Vas a inspeccionar el reflejo. \n2. Vas por el camino entre los árboles. \n3.Ignoras la señal del suelo y te diriges hacia el Norte.");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papyrus.jpg"))); // NOI18N
        jLabel1.setLabelFor(jPanel1);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 320, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 20, 320, 230);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgroundgen_1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-110, -20, 630, 690);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        partida_Guardada recuerdos = new partida_Guardada();
        recuerdos.setVisible(true);
        this.dispose();    
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
